name: "test"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
env:
  jdk_latest: 21

jobs:
  test-linux:
    name: "Linux"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 8
          - JDK 11
          - JDK 17
          - JDK 21
          - JDK Latest
        include:
          - jdkconf: JDK 8
            jdkver: "8"
          - jdkconf: JDK 11
            jdkver: "11"
          - jdkconf: JDK 17
            jdkver: "17"
          - jdkconf: JDK 21
            jdkver: "21"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkver || env.jdk_latest }}
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: Build
        run: mvn clean install

  test-win:
    name: "Windows"
    runs-on: "windows-latest"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 8
          - JDK 11
          - JDK 17
          - JDK 21
          - JDK Latest
        include:
          - jdkconf: JDK 8
            jdkver: "8"
          - jdkconf: JDK 11
            jdkver: "11"
          - jdkconf: JDK 17
            jdkver: "17"
          - jdkconf: JDK 21
            jdkver: "21"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkver || env.jdk_latest }}
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: make
      - name: Build win
        shell: cmd
        run: mvn clean install
      - name: run msys
        shell: msys2 {0}
        run: pwd && ls -l

  test-macos:
    name: "MacOS"
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        jdkconf:
          - JDK 8
          - JDK 11
          - JDK 17
          - JDK 21
          - JDK Latest
        include:
          - jdkconf: JDK 8
            jdkver: "8"
          - jdkconf: JDK 11
            jdkver: "11"
          - jdkconf: JDK 17
            jdkver: "17"
          - jdkconf: JDK 21
            jdkver: "21"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdkver || env.jdk_latest }}
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: Run
        run: mvn clean install
